### ISSUE TITLE
Only look for font files

### ISSUE THREAD

**Issue by RoelN** [kabisa/specimen-boilerplate-support#4]
A stray `.DS_Store` inside `src/fonts` will trip up `yarn fontdata`:

```
Failed to generate font data. Error: Multiple font files found. Please specify the path to your font file explicitly.
```

Maybe look for files with a specific extension (`.woff2`) or skip non-parsable files?

**Comment by pascalw** [comment]
Is there an exhaustive list of extensions we can look for?

**Comment by RoelN** [comment]
Just `.woff2` is sufficient!
